#context path
server:
  servlet:
    context-path: /cryptocurrency
  #port
  port: 8080

# H2
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:coin
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false

# Log config
logging:
  level:
    ROOT: WARN

# bitcoin exchange rate api
coindesk:
  bitcoin:
    rate:
      url: https://api.coindesk.com/v1/bpi/currentprice.json

